spring.application.name=demo
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=Adarsh&2004&
spring.redis.host=localhost
spring.redis.port=6379
spring.jpa.hibernate.ddl-auto=update